name: Build & Test (Go)

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        default: '>=1.20'
        type: string
        description: Version of Go to be used for builds
      base-directory:
        required: false
        default: '.'
        type: string
        description: Base directory in which to perform checkout, build and tests.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ inputs.base-directory }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: true

      - name: Build
        working-directory: ${{ inputs.base-directory }}
        run: go build -v ./...

      - name: Test With Coverage
        working-directory: ${{ inputs.base-directory }}
        run: go test -v -coverpkg=./internal/... ./...
